  <tr>
    <td>
      <table width="100%" border="0" cellspacing="1" cellpadding="0" align="center">

        <tr>
          <td align="center" width = "30%" style="color: C0C0C0; font-size: 14pt; font-weight: bold;">
		     <table><tbody><tr><td><img src="https://info.Zip2Tax.com/z2t_Backoffice/images/z2t-icon.png" alt="Zip2Tax Logo" title="Zip2Tax, LLC Tax Data Providers"></td><td style="
    font-size: 25px;
    font-weight: bold;
    color: white;
    padding-left: 10px;
">Backoffice</td></tr></tbody></table>
            </td>
			<!--
            <img src="<%=strPathImages%>z2t-icon.png" alt="Zip2Tax Logo"
              Title="Zip2Tax, LLC Tax Data Providers">
            <br>BACKOFFICE-->
          </td>

          <td align="center" width="40%" valign="bottom" style="color: white; font-size: 22pt; font-weight: bold;">
            <hr>
            <%=PageHeading%>
            <hr>
          </td>

          <td class="white" align="right" width="30%" valign="top">
           <br>
           <a href="<%=strBasePath%>z2t_Logout.asp" style="color: #FFFFFF;">Logout <%=Session("z2t_UserName")%></a>
          </td>
        </tr>
     
        <!--#include virtual="z2t_Backoffice/includes/menu/PageMenu.inc"-->
        
      </table>  
    </td>
  </tr>
