  <table width="1200px" border="0" cellspacing="0" cellpadding="0" align="center">
    <tr> 
	  <td>
	    <table border="0" cellspacing="0" cellpadding="0">
		  <tr>
			<td align="left" style="font-size: 8pt;
								opacity:0.8;
								color: #C0C0C0;
								font-weight: bold;"> 
			  Copyright &copy;&nbsp;<%=DatePart("yyyy", date) %>
			  Zip2Tax, Inc. All Rights Reserved.
			</td>  
		  </tr>
		</table>
      </td>
	</tr>
  </table>
